spring:
  application:
    name: '@name@'
    version: '@version@'
  datasource:
    pool-prepared-statements: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:actuator-sample}?useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME:actuator-sample}
    password: ${DB_PASSWORD:actuator-sample}
  docker:
    compose:
      file: "./docker/docker-compose.yml"
      profiles.active: "prometheus"
  liquibase:
    change-log: classpath:config/liquibase/master.xml

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    prometheus.enabled: true


server:
  port: 8083
