version: '3.5'

services:
  postgres:
    image: postgres:12.1
    container_name: "actuator-sample"
    networks:
      - actuator-sample
    environment:
      POSTGRES_USER: actuator-sample
      POSTGRES_PASSWORD: actuator-sample
      POSTGRES_DB: actuator-sample
    ports:
      - "5432:5432"

# services

  simple-endpoints:
    container_name: simple-endpoints
    image: lombocska/simple-endpoints
    environment:
      DB_HOST: actuator-sample
      DB_PORT: 5432
    ports:
      - "8080:8080"
    networks:
      - actuator-sample

  simple-metrics:
    container_name: simple-metrics
    image: lombocska/simple-metrics
    environment:
      DB_HOST: actuator-sample
      DB_PORT: 5432
    ports:
      - "8081:8080"
    networks:
      - actuator-sample

networks:
  actuator-sample:
    driver: bridge