spring:
  application:
    name: '@name@'
    version: '@version@'
  datasource:
    pool-prepared-statements: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:actuator-sample}?useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME:actuator-sample}
    password: ${DB_PASSWORD:actuator-sample}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      # never, when-authorized, always
      show-details: always #default is never
  health:
    db:
      enabled: true
  info:
    git:
      enabled: true
      ## full or simple
      mode: FULL
    java:
      enabled: true
    env:
      enabled: true

## https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.info.custom-application-information
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"
