spring:
  application:
    name: '@name@'
    version: '@version@'
  datasource:
    pool-prepared-statements: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:actuator-sample}?useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME:actuator-sample}
    password: ${DB_PASSWORD:actuator-sample}
  docker:
    compose:
      file: "./docker/docker-compose.yml"
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
#  boot:
#    admin:
#      client.url: http://localhost:8085
server:
  port: 8080


# Showcases for lecture called Discovery Page in section 2
#management:
#  endpoints:
#    web:
#      base-path: "/"
#      path-mapping.health: "healthcheck"


#management:
#  endpoints:
#    web:
#      discovery.enabled: false
#    enabled-by-default: false


#management:
#  endpoints:
#    enabled-by-default: false
#    web:
#      exposure:
#        include: info, health
#  endpoint:
#    health.enabled: true
#    info.enabled: true



# Showcases for lecture called Health in section 2
#management:
#  endpoint:
#    health:
#      enabled: false
#  endpoint:
#    health:
#      show-details: always
#      show-components: always

# Showcases for lecture called HttpExchanges in section 2
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    enabled-by-default: true
#  httpexchanges:
#    recording:
#      include: request_headers
#  endpoint:
#    httpexchanges:
#      enabled:












# Showcases for lecture called Beans in section 2
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    enabled-by-default: true



# Showcases for lecture called Liquibase in section 2
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    enabled-by-default: true


## Showcases for lecture called Caches, Conditions, Configproprs, Env, Info, Integrationgraph & Loggers Endpoint in section 2
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    enabled-by-default: true
#  endpoint:
#    configprops:
#      show-values: ALWAYS
#    env:
#      show-values: ALWAYS
#  info:
#    defaults:
#      enabled: true
#    env:
#      enabled: true
#info:
#  encoding: '@project.build.sourceEncoding@'


# Showcases for lecture called Metrics, Mappings, Quartz, Scheduledtasks, Session & Threaddump in section 2
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    enabled-by-default: true

# Showcases for lecture called Metrics, Mappings, Quartz, Scheduledtasks, Session & Threaddump in section 2
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
logging:
  file:
    name: simpleapp.log


