spring:
  application:
    name: '@name@'
    version: '@version@'
  datasource:
    pool-prepared-statements: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:actuator-sample}?useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME:actuator-sample}
    password: ${DB_PASSWORD:actuator-sample}
  docker:
    compose:
      file: "./docker/docker-compose.yml"
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
