version: '3.7'

services:
  postgres:
    image: postgres:12.1
    container_name: "actuator-sample"
    networks:
      - actuator-sample
    environment:
      POSTGRES_USER: actuator-sample
      POSTGRES_PASSWORD: actuator-sample
      POSTGRES_DB: actuator-sample
    ports:
      - "5433:5432"
networks:
  actuator-sample:
    driver: bridge